CREATE DATABASE IF NOT EXISTS NOTEVIEWER;
USE NOTEVIEWER;

CREATE TABLE USERS(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	USERNAME VARCHAR(200) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    USER_PASSWORD CHAR(32) NOT NULL,
    PATH_IMG VARCHAR(200) NOT NULL,
    CURRENT_TOKEN CHAR(32),
    PRIMARY KEY(ID)
)ENGINE=INNODB;

CREATE TABLE NOTES(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    CONTENT VARCHAR(350) NOT NULL,
    DATA_PUBLISHED DATE NOT NULL,
    USER_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
    PRIMARY KEY(ID)
)ENGINE=INNODB;
